services:
  zomboid-server:
    image: ghcr.io/ch-braun/zomboid-server-docker:latest
    platform: linux/amd64
    ports:
      - "16261:16261/udp" # Default play port
      - "16262:16262/udp" # UDP offload port
      - "27015:27015/tcp" # RCON
    env_file: .env
    user: "1069"
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 6144M
    volumes:
      - zomboid-server:/opt/zomboid-server
    entrypoint: /bin/bash -c "./start-server.sh -servername $SERVERNAME -adminpassword $SERVERADMINPASSWORD"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  zomboid-server:
    driver: local